import {
  getOrganizations,
  createOrganization,
  updateOrganization,
  deleteOrganization,
  deleteMyOrganization,
  getMyOrganizationDetails,
  updateMyOrganizationName,
  updateMyPaymentCollectionMode,
  getMyPaymentGatewaySettings,
  saveMyPaymentGatewaySettings,
  getMyOrganizationMembers,
  getMyOrganizationInvitations,
  inviteUserToTenant,
  deleteTenantInvitation,
  removeMemberFromTenant,
  leaveMyOrganization,
  transferMyOrganizationOwnership,
  updateMemberRole,
} from "@/server/admin/actions/organization-actions";
import {
  acceptJoinRequestAction,
  rejectJoinRequestAction,
  cancelJoinRequestAction,
  getPendingJoinRequestsAction,
} from "@/server/admin/actions/join-request-actions";

export const organizationService = {
  getOrganizations,
  createOrganization,
  updateOrganization,
  deleteOrganization,
  deleteMyOrganization,
  getMyOrganizationDetails,
  updateMyOrganizationName,
  updateMyPaymentCollectionMode,
  getMyPaymentGatewaySettings,
  saveMyPaymentGatewaySettings,
  getMyOrganizationMembers,
  getMyOrganizationInvitations,
  inviteUser: inviteUserToTenant,
  deleteInvitation: deleteTenantInvitation,
  removeMember: removeMemberFromTenant,
  leaveOrganization: leaveMyOrganization,
  transferOwnership: transferMyOrganizationOwnership,
  updateMemberRole,
  acceptJoinRequest: acceptJoinRequestAction,
  rejectJoinRequest: rejectJoinRequestAction,
  cancelJoinRequest: cancelJoinRequestAction,
  getPendingJoinRequests: getPendingJoinRequestsAction,
};
