import type { BuilderNode } from "@/types/builder";

export const initialBuilderNodes: BuilderNode[] = [
  // ═══ LANDING ══════════════════════════════════════════
  {
    id: "ld-start-overlay",
    type: "button",
    page: "landing",
    x: 0,
    y: 0,
    width: 1280,
    height: 800,
    rotation: 0,
    opacity: 0.01,
    locked: false,
    visible: true,
    zIndex: 1,
    props: {
      label: "",
      background: "transparent",
      color: "transparent",
      radius: 0,
      semanticRole: "landing.start_session",
    },
  },
  {
    id: "ld-title",
    type: "text",
    page: "landing",
    x: 290,
    y: 270,
    width: 700,
    height: 120,
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    zIndex: 10,
    props: {
      content: "POSKART",
      fontSize: 96,
      fontWeight: 700,
      color: "#C4121A",
      textAlign: "center",
    },
  },
  {
    id: "ld-subtitle",
    type: "text",
    page: "landing",
    x: 320,
    y: 384,
    width: 640,
    height: 64,
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    zIndex: 10,
    props: {
      content: "Receipt Photobooth",
      fontSize: 40,
      fontWeight: 400,
      color: "#1B1B1B",
      textAlign: "center",
      fontStyle: "italic",
    },
  },
  {
    id: "ld-cta",
    type: "text",
    page: "landing",
    x: 40,
    y: 754,
    width: 280,
    height: 28,
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    zIndex: 10,
    props: {
      content: "Click anywhere to start!",
      fontSize: 16,
      color: "#C4121A",
    },
  },
  {
    id: "ld-settings",
    type: "button",
    page: "landing",
    x: 1160,
    y: 24,
    width: 88,
    height: 40,
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    zIndex: 20,
    props: {
      label: "⚙ Settings",
      background: "transparent",
      color: "#52525b",
      radius: 8,
      semanticRole: "landing.settings",
    },
  },
  // ═══ TEMPLATE ══════════════════════════════════════════
  {
    id: "tp-heading",
    type: "text",
    page: "template",
    x: 120,
    y: 24,
    width: 400,
    height: 56,
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    zIndex: 10,
    props: {
      content: "Pilih Template",
      fontSize: 44,
      fontWeight: 700,
      color: "#C4121A",
    },
  },
  {
    id: "tp-subtitle",
    type: "text",
    page: "template",
    x: 120,
    y: 76,
    width: 400,
    height: 36,
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    zIndex: 10,
    props: {
      content: "frame postcard kamu",
      fontSize: 24,
      color: "#1B1B1B",
      fontStyle: "italic",
    },
  },
  {
    id: "tp-preview",
    type: "template-preview",
    page: "template",
    x: 136,
    y: 120,
    width: 296,
    height: 552,
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    zIndex: 10,
    props: { semanticRole: "template.select" },
  },
  {
    id: "tp-name",
    type: "text",
    page: "template",
    x: 136,
    y: 680,
    width: 296,
    height: 28,
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    zIndex: 10,
    props: {
      content: "Classic Postcard",
      fontSize: 18,
      fontWeight: 600,
      color: "#1B1B1B",
      fontStyle: "italic",
    },
  },
  {
    id: "tp-desc",
    type: "text",
    page: "template",
    x: 136,
    y: 710,
    width: 296,
    height: 24,
    rotation: 0,
    opacity: 0.7,
    locked: false,
    visible: true,
    zIndex: 10,
    props: { content: "Cream paper template", fontSize: 13, color: "#52525b" },
  },
  {
    id: "tp-list",
    type: "template-list",
    page: "template",
    x: 560,
    y: 64,
    width: 680,
    height: 640,
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    zIndex: 10,
    props: {
      minTileWidth: 280,
      tileCount: 4,
      templateLayout: "auto",
      templateColumns: 0,
      templateGap: 8,
    },
  },
  {
    id: "tp-back",
    type: "button",
    page: "template",
    x: 40,
    y: 748,
    width: 140,
    height: 44,
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    zIndex: 10,
    props: {
      label: "← Kembali",
      background: "transparent",
      color: "#1B1B1B",
      radius: 8,
      semanticRole: "template.back",
    },
  },
  {
    id: "tp-count",
    type: "text",
    page: "template",
    x: 968,
    y: 758,
    width: 80,
    height: 32,
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    zIndex: 10,
    props: {
      content: "3 foto",
      fontSize: 14,
      fontWeight: 600,
      color: "#1B1B1B",
      textAlign: "center",
    },
  },
  {
    id: "tp-continue",
    type: "button",
    page: "template",
    x: 1056,
    y: 724,
    width: 180,
    height: 64,
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    zIndex: 10,
    props: {
      label: "Lanjutkan →",
      background: "#C4121A",
      color: "#ffffff",
      radius: 32,
      fontSize: 16,
      semanticRole: "template.continue",
    },
  },
  // ═══ CAMERA ══════════════════════════════════════════
  {
    id: "cam-view",
    type: "camera-view",
    page: "camera",
    x: 32,
    y: 64,
    width: 680,
    height: 520,
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    zIndex: 5,
    props: {},
  },
  {
    id: "cam-take-photo",
    type: "button",
    page: "camera",
    x: 848,
    y: 136,
    width: 192,
    height: 192,
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    zIndex: 10,
    props: {
      label: "Take Photo",
      background: "#C4121A",
      color: "#ffffff",
      radius: 96,
      fontSize: 14,
      semanticRole: "camera.take_photo",
    },
  },
  {
    id: "cam-photo-result",
    type: "photo-result",
    page: "camera",
    x: 784,
    y: 344,
    width: 440,
    height: 192,
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    zIndex: 7,
    props: {
      semanticRole: "camera.photo_result",
      photoLayout: "auto",
      photoColumns: 0,
      samplePhotoCount: 4,
    },
  },
  {
    id: "cam-counter",
    type: "text",
    page: "camera",
    x: 784,
    y: 542,
    width: 440,
    height: 28,
    rotation: 0,
    opacity: 0.7,
    locked: false,
    visible: true,
    zIndex: 10,
    props: {
      content: "0 / 2 captured",
      fontSize: 14,
      color: "#52525b",
      textAlign: "center",
    },
  },
  {
    id: "cam-social",
    type: "social-handle",
    page: "camera",
    x: 40,
    y: 752,
    width: 200,
    height: 28,
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    zIndex: 10,
    props: { content: "@poskart", fontSize: 15, color: "#1B1B1B" },
  },
  // ═══ PREVIEW ══════════════════════════════════════════
  {
    id: "pv-heading-1",
    type: "text",
    page: "preview",
    x: 40,
    y: 56,
    width: 180,
    height: 56,
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    zIndex: 10,
    props: {
      content: "Your",
      fontSize: 44,
      fontWeight: 400,
      color: "#C4121A",
      fontStyle: "italic",
    },
  },
  {
    id: "pv-heading-2",
    type: "text",
    page: "preview",
    x: 214,
    y: 60,
    width: 480,
    height: 48,
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    zIndex: 10,
    props: {
      content: "Receipt is ready.",
      fontSize: 40,
      fontWeight: 700,
      color: "#1B1B1B",
    },
  },
  {
    id: "pv-frame",
    type: "frame-preview",
    page: "preview",
    x: 176,
    y: 112,
    width: 336,
    height: 552,
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    zIndex: 8,
    props: { src: "", alt: "Preview Frame", radius: 8 },
  },
  {
    id: "pv-media-toggle",
    type: "preview-media-toggle",
    page: "preview",
    x: 244,
    y: 72,
    width: 240,
    height: 48,
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    zIndex: 12,
    props: {
      defaultMode: "photo",
      photoLabel: "Photo",
      gifLabel: "GIF",
      livePhotoLabel: "Live",
    },
  },
  {
    id: "pv-scan-label",
    type: "text",
    page: "preview",
    x: 660,
    y: 128,
    width: 320,
    height: 40,
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    zIndex: 10,
    props: {
      content: "Scan to download",
      fontSize: 22,
      color: "#1B1B1B",
      fontStyle: "italic",
      textAlign: "center",
    },
  },
  {
    id: "pv-qr",
    type: "qr",
    page: "preview",
    x: 672,
    y: 172,
    width: 296,
    height: 252,
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    zIndex: 10,
    props: {
      label: "Download",
      semanticRole: "preview.qr_download",
      showQrLink: true,
      qrTransparentBackground: false,
      showShareButton: false,
      shareButtonLabel: "Share",
      shareButtonBackground: "#18181b",
      shareButtonColor: "#ffffff",
    },
  },
  {
    id: "pv-url",
    type: "text",
    page: "preview",
    x: 640,
    y: 432,
    width: 360,
    height: 28,
    rotation: 0,
    opacity: 0.7,
    locked: false,
    visible: true,
    zIndex: 10,
    props: {
      content: "https://poskart.app/s/...",
      fontSize: 12,
      color: "#3b82f6",
      textAlign: "center",
    },
  },
  {
    id: "pv-print",
    type: "button",
    page: "preview",
    x: 676,
    y: 468,
    width: 120,
    height: 80,
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    zIndex: 10,
    props: {
      label: "Print",
      background: "#C4121A",
      color: "#ffffff",
      radius: 40,
      fontSize: 14,
      semanticRole: "preview.print",
    },
  },
  {
    id: "pv-finish",
    type: "button",
    page: "preview",
    x: 948,
    y: 468,
    width: 120,
    height: 80,
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    zIndex: 10,
    props: {
      label: "Finish",
      background: "#C4121A",
      color: "#ffffff",
      radius: 40,
      fontSize: 14,
      semanticRole: "preview.finish",
    },
  },
  {
    id: "pv-share",
    type: "button",
    page: "preview",
    x: 812,
    y: 468,
    width: 120,
    height: 80,
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    zIndex: 10,
    props: {
      label: "Share",
      background: "#1B1B1B",
      color: "#ffffff",
      radius: 40,
      fontSize: 14,
      semanticRole: "preview.share",
    },
  },
  {
    id: "pv-badge",
    type: "text",
    page: "preview",
    x: 24,
    y: 740,
    width: 80,
    height: 28,
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    zIndex: 10,
    props: {
      content: "Minimal",
      fontSize: 12,
      fontWeight: 600,
      color: "#52525b",
    },
  },
  {
    id: "pv-caption",
    type: "text",
    page: "preview",
    x: 112,
    y: 742,
    width: 640,
    height: 24,
    rotation: 0,
    opacity: 0.8,
    locked: false,
    visible: true,
    zIndex: 10,
    props: {
      content:
        "Send your printed memory home — scan the QR to download digital copies.",
      fontSize: 13,
      color: "#52525b",
    },
  },

  // ═══ THANKS ══════════════════════════════════════════
  {
    id: "th-heading-1",
    type: "text",
    page: "thanks",
    x: 56,
    y: 216,
    width: 560,
    height: 56,
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    zIndex: 10,
    props: {
      content: "Thanks for visiting",
      fontSize: 40,
      fontWeight: 400,
      color: "#1B1B1B",
      fontStyle: "italic",
    },
  },
  {
    id: "th-heading-2",
    type: "text",
    page: "thanks",
    x: 56,
    y: 264,
    width: 560,
    height: 112,
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    zIndex: 10,
    props: {
      content: "POSKART.",
      fontSize: 88,
      fontWeight: 700,
      color: "#C4121A",
    },
  },
  {
    id: "th-tagline",
    type: "text",
    page: "thanks",
    x: 56,
    y: 370,
    width: 560,
    height: 56,
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    zIndex: 10,
    props: {
      content: "Your memories have been printed.",
      fontSize: 28,
      fontWeight: 400,
      color: "#1B1B1B",
      fontStyle: "italic",
    },
  },
  {
    id: "th-body",
    type: "text",
    page: "thanks",
    x: 56,
    y: 436,
    width: 560,
    height: 36,
    rotation: 0,
    opacity: 0.7,
    locked: false,
    visible: true,
    zIndex: 10,
    props: {
      content:
        "Don't forget to scan the QR code on your receipt to download a digital copy.",
      fontSize: 13,
      color: "#52525b",
    },
  },
  {
    id: "th-countdown",
    type: "return-countdown",
    page: "thanks",
    x: 56,
    y: 488,
    width: 256,
    height: 44,
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    zIndex: 10,
    props: {
      countdownText: "Returning to start",
      countdownSeconds: 8,
      semanticRole: "thanks.countdown_timer",
    },
  },
  {
    id: "th-frame",
    type: "frame-preview",
    page: "thanks",
    x: 720,
    y: 176,
    width: 304,
    height: 480,
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    zIndex: 8,
    props: { src: "", alt: "Printed Frame", radius: 8 },
  },
];
